### ISSUE TITLE
Deployment trouble from docker container to CCE

### ISSUE THREAD

**Issue by trickytibo** [FlexibleEngineCloud/terraform-flexibleengine-cce#10]
When trying to deploy the infrastructure to CCE from docker container (via gitlab ci runner) I get : 
Error: Error creating flexibleengine Cluster: Bad request with: [POST https://cce.eu-west-0.prod-cloud-ocb.orange-business.com/api/v3/projects/439be87c830e47b1af889ad726cd351a/clusters], error message: {"error_code":"CCE_CM.0402","error_msg":"Version is not support","errorCode":"E.CFE.4000402","reason":"Version is not support"}

I used image hashicorp/terraform:0.13/14/15.0. The deployment is OK from a virtual machine (same sources) with the version of terraform (Terraform v0.15.0 on linux_amd64). 

Do you know why ? 

Thanks for your help

**Comment by antonin-a** [comment]
Hello @trickytibo can you please share your terraform plan ? 
It looks like the CCE version specified is not correct, currently supported versions are described here: https://docs.prod-cloud-ocb.orange-business.com/en-us/usermanual2/cce/cce_01_0068.html

**Comment by trickytibo** [comment]
Below the plan : 

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
Terraform will perform the following actions:
  # module.cce2_cluster.flexibleengine_cce_cluster_v3.cce_cluster will be created
  + resource "flexibleengine_cce_cluster_v3" "cce_cluster" {
      + authentication_mode    = "rbac"
      + billing_mode           = (known after apply)
      + certificate_clusters   = (known after apply)
      + certificate_users      = (known after apply)
      + cluster_type           = "VirtualMachine"
      + cluster_version        = "var.CLUSTER_VERSION"
      + container_network_cidr = (known after apply)
      + container_network_type = "overlay_l2"
      + description            = " Cluster for Reporting MA Project"
      + external_apig_endpoint = (known after apply)
      + external_endpoint      = (known after apply)
      + flavor_id              = "cce.s2.small"
      + highway_subnet_id      = (known after apply)
      + id                     = (known after apply)
      + internal_endpoint      = (known after apply)
      + name                   = "REPORTING_V2_TEST"
      + region                 = (known after apply)
      + security_group_id      = (known after apply)
      + status                 = (known after apply)
      + subnet_id              = "var.NETWORK_ID"
      + vpc_id                 = "var.VPC_ID"
      + masters {
          + availability_zone = (known after apply)
        }
    }
  # module.cce2_cluster.flexibleengine_cce_node_pool_v3.cce_node_pool["nodepool0"] will be created
  + resource "flexibleengine_cce_node_pool_v3" "cce_node_pool" {
      + availability_zone  = "random"
      + billing_mode       = (known after apply)
      + cluster_id         = (known after apply)
      + flavor_id          = "s3.large.2"
      + id                 = (known after apply)
      + initial_node_count = 1
      + key_pair           = "var.SSH_KEY_NAME"
      + labels             = {
          + "taints" = "test-taint"
        }
      + max_node_count     = 5
      + min_node_count     = 1
      + name               = "cce-nodepool-test"
      + os                 = "CentOS 7.5"
      + region             = (known after apply)
      + scall_enable       = true
      + status             = (known after apply)
      + type               = "vm"
      + data_volumes {
          + size       = 100
          + volumetype = "SATA"
        }
      + root_volume {
          + size       = 40
          + volumetype = "SATA"
        }
      + taints {
          + effect = "NoSchedule"
          + key    = "key1"
          + value  = "value1"
        }
      + taints {
          + effect = "NoExecute"
          + key    = "key1"
          + value  = "value1"
        }
      + taints {
          + effect = "NoSchedule"
          + key    = "key2"
          + value  = "value2"
        }
    }
  # module.cce2_cluster.flexibleengine_cce_node_v3.cce_cluster_node["node0"] will be created
  + resource "flexibleengine_cce_node_v3" "cce_cluster_node" {
      + availability_zone          = "eu-west-0a"
      + bandwidth_charge_mode      = (known after apply)
      + bandwidth_size             = (known after apply)
      + billing_mode               = (known after apply)
      + cluster_id                 = (known after apply)
      + ecs_performance_type       = (known after apply)
      + eip_count                  = (known after apply)
      + eip_ids                    = (known after apply)
      + extend_param_charging_mode = (known after apply)
      + flavor_id                  = "s3.large.2"
      + id                         = (known after apply)
      + iptype                     = (known after apply)
      + key_pair                   = "var.SSH_KEY_NAME"
      + max_pods                   = (known after apply)
      + name                       = "cce-node1"
      + order_id                   = (known after apply)
      + os                         = "CentOS 7.5"
      + private_ip                 = (known after apply)
      + product_id                 = (known after apply)
      + public_ip                  = (known after apply)
      + public_key                 = (known after apply)
      + region                     = (known after apply)
      + server_id                  = (known after apply)
      + sharetype                  = (known after apply)
      + data_volumes {
          + size       = 100
          + volumetype = "SATA"
        }
      + root_volume {
          + size       = 40
          + volumetype = "SATA"
        }
    }
  # module.cce2_cluster.flexibleengine_cce_node_v3.cce_cluster_node["node1"] will be created
  + resource "flexibleengine_cce_node_v3" "cce_cluster_node" {
      + availability_zone          = "eu-west-0b"
      + bandwidth_charge_mode      = (known after apply)
      + bandwidth_size             = (known after apply)
      + billing_mode               = (known after apply)
      + cluster_id                 = (known after apply)
      + ecs_performance_type       = (known after apply)
      + eip_count                  = (known after apply)
      + eip_ids                    = (known after apply)
      + extend_param_charging_mode = (known after apply)
      + flavor_id                  = "s3.large.2"
      + id                         = (known after apply)
      + iptype                     = (known after apply)
      + key_pair                   = "var.SSH_KEY_NAME"
      + labels                     = {
          + "type" = "extra-node"
        }
      + max_pods                   = (known after apply)
      + name                       = "cce-node2"
      + order_id                   = (known after apply)
      + os                         = "CentOS 7.5"
      + private_ip                 = (known after apply)
      + product_id                 = (known after apply)
      + public_ip                  = (known after apply)
      + public_key                 = (known after apply)
      + region                     = (known after apply)
      + server_id                  = (known after apply)
      + sharetype                  = (known after apply)
      + tags                       = {
          + "Env"   = "Prod"
          + "Owner" = "Me"
        }
      + data_volumes {
          + size       = 100
          + volumetype = "SATA"
        }
      + root_volume {
          + size       = 40
          + volumetype = "SATA"
        }
      + taints {
          + effect = "NoSchedule"
          + key    = "key1"
          + value  = "value1"
        }
      + taints {
          + effect = "NoExecute"
          + key    = "key1"
          + value  = "value1"
        }
      + taints {
          + effect = "NoSchedule"
          + key    = "key2"
          + value  = "value2"
        }
    }
Plan: 4 to add, 0 to change, 0 to destroy.

**Comment by trickytibo** [comment]
The k8s version I ask is v1.17.9-r0

**Comment by trickytibo** [comment]
The default comes from my code. I put my variables (ex var.toto) inside double quotes. My bad. Thanks for your help, you can close the case.

**Comment by antonin-a** [comment]
ok, it happens :)
