### ISSUE TITLE
Add container_network_type as input of the module

### ISSUE THREAD

**Issue by SBatais** [FlexibleEngineCloud/terraform-flexibleengine-cce#16]
Module version : 2.3.3
I would like to know if it's possible to add the parameter container_network_type of the resource flexibleengine_cce_cluster_v3, as an input of the module, in order to be able to set it with a value different than "overlay_l2"
Thanks in advance for this improvment

**Comment by stephbat** [comment]
see pull request https://github.com/FlexibleEngineCloud/terraform-flexibleengine-cce/pull/17
