### ISSUE TITLE
Define minimal version of the flexibleengine provider to use

### ISSUE THREAD

**Issue by pierrecarre** [FlexibleEngineCloud/terraform-flexibleengine-cce#3]
Hello,

I think it could be interesting to define the minimal version of the flexibleengine provider to use, like for Terraform.

We could change the following block
https://github.com/terraform-flexibleengine-modules/terraform-flexibleengine-cce/blob/ffba20de09c34d59d3efcd58f66a6005fca043b7/main.tf#L1-L3

Like this
```
terraform { 
   required_version = ">= 0.12.0"
   required_providers {
     flexibleengine = ">= 1.10"
   }
} 
```

**Comment by antonin-a** [comment]
@pierrecarre fixed using the versions.tf file: https://github.com/FlexibleEngineCloud/terraform-flexibleengine-cce/blob/master/versions.tf
