### ISSUE TITLE
Unable to create flexibleengine CCE client : No suitable endpoint could be found in the service catalog

### ISSUE THREAD

**Issue by trickytibo** [FlexibleEngineCloud/terraform-flexibleengine-cce#9]
When trying to deploy a CCE cluster (version v1.17.9-r0) thanks to your module (same code as the github), I get the error specified in the title. Terraform plan is OK. Error comes with the apply stage.

**Comment by antonin-a** [comment]
Hello @vlandemaine-orange , do you that you can help us on this one ?

**Comment by antonin-a** [comment]
@trickytibo can you provide us your cloud config / env variables ?

**Comment by trickytibo** [comment]
terraform {
  required_providers {
    flexibleengine = {
      source = "FlexibleEngineCloud/flexibleengine"
    }
  }
  required_version = ">= 0.13"
}

provider "flexibleengine" {
  auth_url = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3"
  #region   = "eu-west-0a"
  domain_name = "xxx"
  tenant_name = "eu-west-0"
  user_name = "xxx"
  password = "xxx"
}

variable "VPC_ID" {
  description = "Value of the main VPC"
  type        = string
  default     = "xxx"
}

variable "NETWORK_ID" {
  description = "Value of the main Network"
  type        = string
  default     = "xxx"
}

variable "SSH_KEY_NAME" {
  description = "Value of the main Network"
  type        = string
  default     = "xxx"
}

variable "CLUSTER_VERSION" {
  description = "The kubernetes cluster version"
  type        = string
  default     = "v1.17.9-r0"
}

module "cce2_cluster" {
    source = "FlexibleEngineCloud/cce/flexibleengine"
    version = "2.3.0"

    cluster_name  = "cluster-test"
    cluster_desc = " Cluster for testing purpose"

    cluster_flavor = "cce.s1.small"
    vpc_id = var.VPC_ID
    network_id = var.NETWORK_ID  //Caution here, you have to use NETWORK_ID even if argument is "subnet_id". Will be fixed soon
    cluster_version = var.CLUSTER_VERSION
    node_os  = "CentOS 7.5" // Can be "EulerOS 2.5" or "CentOS 7.5"
    key_pair = var.SSH_KEY_NAME

    nodes_list = [
      {
        node_index         = "node0"
        node_name          = "cce-node1"
        node_flavor        = "s3.large.2"
        availability_zone  = "eu-west-0a"
        root_volume_type   = "SATA"
        root_volume_size   = 40
        data_volume_type   = "SATA"
        data_volume_size   = 100
        node_labels        = {}
        vm_tags            = {}
        postinstall_script =  null
        preinstall_script  = null
        taints             = []
      },
      {
        node_index        = "node1"
        node_name         = "cce-node2"
        node_flavor       = "s3.large.2"
        availability_zone = "eu-west-0b"
        root_volume_type  = "SATA"
        root_volume_size  = 40
        data_volume_type  = "SATA"
        data_volume_size  = 100
        node_labels = {
          type = "extra-node"
        }
        vm_tags = {
          Owner = "Me"
          Env = "Prod"
        }
        postinstall_script =  null
        preinstall_script  = null
        taints = [
          {
            key    = "key1"
            value  = "value1"
            effect = "NoSchedule"
          },
          {
            key    = "key1"
            value  = "value1"
            effect = "NoExecute"
          },
          {
            key    = "key2"
            value  = "value2"
            effect = "NoSchedule"
          }
        ]
      }
    ]

    node_pool_list = [
      {
        node_pool_index          = "nodepool0"
        node_pool_name           = "cce-nodepool-test"
        node_flavor              = "s3.large.2"
        availability_zone        = null
        initial_node_count       = 1
        scall_enable             = true
        min_node_count           = 1
        max_node_count           = 3
        scale_down_cooldown_time = null
        priority                 = null
        root_volume_type         = "SATA"
        root_volume_size         = 40
        data_volume_type         = "SATA"
        data_volume_size         = 100
        node_labels = {
          taints = "test-taint"
        }
        preinstall_script  = null
        postinstall_script = null
        taints = [
          {
            key    = "key1"
            value  = "value1"
            effect = "NoSchedule"
          },
          {
            key    = "key1"
            value  = "value1"
            effect = "NoExecute"
          },
          {
            key    = "key2"
            value  = "value2"
            effect = "NoSchedule"
          }
        ]
      }
    ]

}

**Comment by antonin-a** [comment]
thank you @trickytibo , can you please try with 
`region = "eu-west-0"`

**Comment by trickytibo** [comment]
It s working way better ! Thanks.

**Comment by antonin-a** [comment]
@trickytibo Great ;) Closing this one
